//----------------------------------------------------------------------------------

// displayNtupleSimParticleInfo(string filelist)
// Written by Andrew Boldy
// University of South Carolina
// July 2026

//----------------------------------------------------------------------------------

// Displays particle information for a list of files, specifically PDG number,
// number of hits on the detector, process code, and rank.
// Must be run using C++ compile mode to rectify issues generated by common_cuts.hh.

//----------------------------------------------------------------------------------

// Standard Inclusions
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

// Mu2e Inclusions
#include "EventNtuple/rooutil/inc/RooUtil.hh"
#include "EventNtuple/rooutil/inc/common_cuts.hh"

void displayNtupleSimParticleInfo(string filelist)
{
  // Manual switch: set this to false to suppress event-by-event SimParticle timing.
  // The switch is intentionally enabled here for timing investigations.
  const bool printSimParticleTiming = true;

  // Manual selection switch: when true, print only events containing exactly
  // two reconstructed e-minus tracks and only rank-0 SimParticle matches.
  const bool selectTwoTrackRankZeroOnly = true;

  // Independent manual switch for the total particle counter.  These totals
  // are accumulated before the event/rank selection above is applied.
  const bool printParticleCountingSummary = true;

  // Manual switch for the event-level MC-truth timing difference.  Particle 1
  // is the rank-0 SimParticle matched to track 0, particle 2 is the rank-0
  // SimParticle matched to track 1, and the printed value is t1 - t2.
  const bool DO_TIMING_DIFFERENCE = true;

  ifstream listOfFiles(filelist);
  int fileCount = 0;
  string line;
  while (getline(listOfFiles, line))
  {
    if (!line.empty())
    {
      fileCount++;
    }
  }

  int eMinusCounter = 0;
  int ePlusCounter = 0;
  int protonCounter = 0;
  int muMinusCounter = 0;
  int neutronCounter = 0;
  int piMinusCounter = 0;
  int piPlusCounter = 0;
  int piZeroCounter = 0;
  int lambdaCounter = 0;
  int sigmaPlusCounter = 0;
  int sigmaZeroCounter = 0;
  int sigmaMinusCounter = 0;
  int kShortCounter = 0;
  int kLongCounter = 0;
  int kMinusCounter = 0;
  int kPlusCounter = 0;
  int photonCounter = 0;
  int cascadeZeroCounter = 0;
  int cascadeMinusCounter = 0;
  vector<int> extraParticleIDArray;

  RooUtil util(filelist);
  int numEvents = util.GetNEvents();
  cout << "============================================================" << endl;
  cout << "Ntuple SimParticle Information" << endl;
  cout << "Input file list: " << filelist << endl;
  cout << "Files listed: " << fileCount << endl;
  cout << "Events: " << numEvents << endl;
  cout << "SimParticle timing: "
       << (printSimParticleTiming ? "ON" : "OFF") << endl;
  cout << "Two-track, rank-0 selection: "
       << (selectTwoTrackRankZeroOnly ? "ON" : "OFF") << endl;
  cout << "Total particle counting summary: "
       << (printParticleCountingSummary ? "ON" : "OFF") << endl;
  cout << "MC-truth timing difference: "
       << (DO_TIMING_DIFFERENCE ? "ON" : "OFF") << endl;
  cout << "============================================================" << endl;

  for (int i_event = 0; i_event < numEvents; i_event++)
  {
    auto& event = util.GetEvent(i_event);
    auto e_minus_tracks = event.GetTracks(is_e_minus);

    // Count every stored SimParticle attached to the reconstructed e-minus
    // tracks before applying any event or rank selection used for printing.
    if (printParticleCountingSummary)
    {
      for (auto& track : e_minus_tracks)
      {
        if (track.trkmcsim == nullptr)
        {
          continue;
        }

        for (const auto& mctrack : *(track.trkmcsim))
        {
          if (mctrack.pdg == 11) eMinusCounter++;
          if (mctrack.pdg == -11) ePlusCounter++;
          if (mctrack.pdg == 2212) protonCounter++;
          if (mctrack.pdg == 2112) neutronCounter++;
          if (mctrack.pdg == 13) muMinusCounter++;
          if (mctrack.pdg == -211) piMinusCounter++;
          if (mctrack.pdg == 211) piPlusCounter++;
          if (mctrack.pdg == 111) piZeroCounter++;
          if (mctrack.pdg == 3122) lambdaCounter++;
          if (mctrack.pdg == 3222) sigmaPlusCounter++;
          if (mctrack.pdg == 3212) sigmaZeroCounter++;
          if (mctrack.pdg == 3112) sigmaMinusCounter++;
          if (mctrack.pdg == 310) kShortCounter++;
          if (mctrack.pdg == 130) kLongCounter++;
          if (mctrack.pdg == -321) kMinusCounter++;
          if (mctrack.pdg == 321) kPlusCounter++;
          if (mctrack.pdg == 22) photonCounter++;
          if (mctrack.pdg == 3322) cascadeZeroCounter++;
          if (mctrack.pdg == 3312) cascadeMinusCounter++;

          if (mctrack.pdg != 3312 && mctrack.pdg != 3322 &&
              mctrack.pdg != 321 && mctrack.pdg != 22 &&
              mctrack.pdg != -321 && mctrack.pdg != 310 &&
              mctrack.pdg != 130 && mctrack.pdg != 3222 &&
              mctrack.pdg != 3112 && mctrack.pdg != 3212 &&
              mctrack.pdg != 3122 && mctrack.pdg != 13 &&
              mctrack.pdg != 11 && mctrack.pdg != -11 &&
              mctrack.pdg != 2212 && mctrack.pdg != 2112 &&
              mctrack.pdg != -211 && mctrack.pdg != 211 &&
              mctrack.pdg != 111)
          {
            extraParticleIDArray.push_back(mctrack.pdg);
          }
        }
      }
    }

    if (selectTwoTrackRankZeroOnly && e_minus_tracks.size() != 2)
    {
      continue;
    }

    // Locate the first rank-0 SimParticle match for each of the two selected
    // tracks.  trkmcsim is stored per reconstructed track, so these are the
    // two MC-truth particles corresponding to particle 1 and particle 2.
    const mu2e::SimInfo* particleOneTruth = nullptr;
    const mu2e::SimInfo* particleTwoTruth = nullptr;
    if (DO_TIMING_DIFFERENCE && e_minus_tracks.size() >= 2)
    {
      if (e_minus_tracks.at(0).trkmcsim != nullptr)
      {
        for (const auto& mctrack : *(e_minus_tracks.at(0).trkmcsim))
        {
          if (mctrack.rank == 0)
          {
            particleOneTruth = &mctrack;
            break;
          }
        }
      }

      if (e_minus_tracks.at(1).trkmcsim != nullptr)
      {
        for (const auto& mctrack : *(e_minus_tracks.at(1).trkmcsim))
        {
          if (mctrack.rank == 0)
          {
            particleTwoTruth = &mctrack;
            break;
          }
        }
      }
    }

    cout << endl;
    cout << "Event " << i_event;
    if (DO_TIMING_DIFFERENCE)
    {
      if (particleOneTruth != nullptr && particleTwoTruth != nullptr)
      {
        cout << " | MC truth delta_t (particle 1 - particle 2): "
             << particleOneTruth->time - particleTwoTruth->time << " ns";
      }
      else
      {
        cout << " | MC truth delta_t (particle 1 - particle 2): unavailable";
      }
    }
    cout << " | reconstructed e-minus tracks: " << e_minus_tracks.size() << endl;
    cout << "------------------------------------------------------------" << endl;

    for (size_t i_track = 0; i_track < e_minus_tracks.size(); i_track++)
    {
      auto& track = e_minus_tracks.at(i_track);
      if (track.trkmcsim != nullptr)
      {
        size_t simParticlesToPrint = track.trkmcsim->size();
        if (selectTwoTrackRankZeroOnly)
        {
          simParticlesToPrint = 0;
          for (const auto& mctrack : *(track.trkmcsim))
          {
            if (mctrack.rank == 0)
            {
              simParticlesToPrint++;
            }
          }
        }

        cout << "Track " << i_track
             << " | SimParticles printed: " << simParticlesToPrint << endl;

        size_t i_simparticle = 0;
        for (const auto& mctrack : *(track.trkmcsim))
        {
          if (selectTwoTrackRankZeroOnly && mctrack.rank != 0)
          {
            i_simparticle++;
            continue;
          }

          // Delimited labels avoid depending on ROOT's persistent cout padding
          // state, which may be changed elsewhere between event reads.
          cout << "  SimParticle " << i_simparticle
               << " | ID: " << mctrack.id
               << " | PDG: " << mctrack.pdg
               << " | Hits: " << mctrack.nhits
               << " | Process: " << mctrack.startCode
               << " | Rank: " << mctrack.rank;
          if (printSimParticleTiming)
          {
            cout << " | Time: " << mctrack.time << " ns";
          }
          cout << endl;
          i_simparticle++;
        }
      }
      else
      {
        cout << "Track " << i_track << " | SimParticle data unavailable" << endl;
      }
    }
  }

  if (printParticleCountingSummary)
  {
    cout << endl;
    cout << "============================================================" << endl;
    cout << "Total Particle Summary (before event/rank selections)" << endl;
    cout << "============================================================" << endl;

    if (extraParticleIDArray.empty())
    {
      cout << "All particles accounted for!" << endl;
    }
    else
    {
      cout << "Extraneous particles pdgs: " << endl;
      for (size_t particle_i = 0; particle_i < extraParticleIDArray.size(); particle_i++)
      {
        cout << particle_i << ". Particle type id: "
             << extraParticleIDArray[particle_i] << endl;
      }
    }

    cout << "Number of electrons in tracks: " << eMinusCounter << endl;
    cout << "Number of protons in tracks: " << protonCounter << endl;
    cout << "Number of neutrons in tracks: " << neutronCounter << endl;
    cout << "Number of muons in tracks: " << muMinusCounter << endl;
    cout << "Number of Positive | Zero | Negative pi mesons in tracks: "
         << piPlusCounter << " | " << piZeroCounter << " | " << piMinusCounter << endl;
    cout << "Number of lambda baryons in tracks: " << lambdaCounter << endl;
    cout << "Number of Positive | Neutral | Negative sigma baryons in tracks: "
         << sigmaPlusCounter << " | " << sigmaZeroCounter << " | " << sigmaMinusCounter << endl;
    cout << "Number of positrons in tracks: " << ePlusCounter << endl;
    cout << "Number of Positive | Negative | Short-lived | Long-lived Kaons in tracks: "
         << kPlusCounter << " | " << kMinusCounter << " | "
         << kShortCounter << " | " << kLongCounter << endl;
    cout << "Number of photons in tracks: " << photonCounter << endl;
    cout << "Number of Zero | Minus Cascade Baryons in tracks: "
         << cascadeZeroCounter << " | " << cascadeMinusCounter << endl;
  }
}

